# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2880c5c71a7339e5b52233c459649088631c3d57973018c963079b91ae6113569d3c6922dd26d96050477ff32382e65274125a48049e72eea5b80d31510dcbb

test:
  secret_key_base: 803c0d8b6a7945881480c72706740e95118373b6df1af767493d53a556eccc567293175e9e1ee74c33e940cab192057ae26576a1b703238c487b5481a54a9f56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
